apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-canary
  namespace: aceest
spec:
  replicas: 1   # small slice of traffic
  selector:
    matchLabels:
      app: aceest
      track: canary
  template:
    metadata:
      labels:
        app: aceest
        track: canary
    spec:
      containers:
        - name: web
          image: DOCKERHUB_USER/aceest-fitness:CANARY_TAG
          ports:
            - containerPort: 5000
