apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-shadow
  namespace: aceest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aceest
      track: shadow
  template:
    metadata:
      labels:
        app: aceest
        track: shadow
    spec:
      containers:
        - name: web
          image: DOCKERHUB_USER/aceest-fitness:SHADOW_TAG
          ports:
            - containerPort: 5000
