apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-green
  namespace: aceest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      color: green
  template:
    metadata:
      labels:
        app: aceest
        color: green
        track: canary
    spec:
      containers:
        - name: web
          image: DOCKERHUB_USER/aceest-fitness:GREEN_TAG
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
