apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-rolling
  namespace: aceest
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: aceest
      track: stable
  template:
    metadata:
      labels:
        app: aceest
        track: stable
    spec:
      containers:
        - name: web
          image: DOCKERHUB_USER/aceest-fitness:ROLLING_TAG
          ports:
            - containerPort: 5000
